/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/aboutPage': RouteRecordInfo<'/aboutPage', '/aboutPage', Record<never, never>, Record<never, never>>,
    '/error/403Page': RouteRecordInfo<'/error/403Page', '/error/403Page', Record<never, never>, Record<never, never>>,
    '/error/404Page': RouteRecordInfo<'/error/404Page', '/error/404Page', Record<never, never>, Record<never, never>>,
    '/indexPage': RouteRecordInfo<'/indexPage', '/indexPage', Record<never, never>, Record<never, never>>,
    '/loginPage': RouteRecordInfo<'/loginPage', '/loginPage', Record<never, never>, Record<never, never>>,
  }
}
