/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarView: typeof import('./components/charts/BarView.vue')['default']
    ChartsView: typeof import('./components/charts/ChartsView.vue')['default']
    DropdownView: typeof import('./components/DropdownView.vue')['default']
    LineView: typeof import('./components/charts/LineView.vue')['default']
    MessageBox: typeof import('./components/MsgBox/MessageBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
